linux-mainline: fix 'devtool modify' command fail
Traceback (most recent call last):
  File "${TOPDIR}/../src/poky/scripts/devtool", line 338, in <module>
    ret = main()
  File "${TOPDIR}/../src/poky/scripts/devtool", line 325, in main
    ret = args.func(args, config, basepath, workspace)
  File "${TOPDIR}/../src/poky/scripts/lib/devtool/standard.py", line 834, in modify
    if (os.path.exists(srcdir) and os.listdir(srcdir)) and (kernelVersion in staging_kerVer and staging_kbranch == kbranch):
TypeError: 'in <string>' requires string as left operand, not NoneType

Where 'kernelVersion' is None that cause an error.
In the code: "kernelVersion = rd.getVar('LINUX_VERSION')"
So LINUX_VERSION should be initialized

Signed-off-by: Ilja Byckevich <iljabyckevich@gmail.com>